### ISSUE TITLE
Thumbsup reaction still failing...

### ISSUE THREAD

**Issue by gabrc52** [gabrc52/mattermost-to-matrix#19]
```
Aug 04 19:09:59 uplink python[1887935]: Exception in Matrix event handler
Aug 04 19:09:59 uplink python[1887935]: Traceback (most recent call last):
Aug 04 19:09:59 uplink python[1887935]:   File "/home/mattermost/mattermost-to-matrix/venv/lib/python3.10/site-packages/mautrix/appservice/as_handler.py", line 333, in try_handle
Aug 04 19:09:59 uplink python[1887935]:     await handler_func(event)
Aug 04 19:09:59 uplink python[1887935]:   File "/home/mattermost/mattermost-to-matrix/bridge.py", line 287, in on_matrix_event
Aug 04 19:09:59 uplink python[1887935]:     await on_matrix_reaction(evt, channel_id)
Aug 04 19:09:59 uplink python[1887935]:   File "/home/mattermost/mattermost-to-matrix/bridge.py", line 243, in on_matrix_reaction
Aug 04 19:09:59 uplink python[1887935]:     mm.create_reaction(own_id, post_id, get_emoji_name(emoji))
Aug 04 19:09:59 uplink python[1887935]:   File "/home/mattermost/mattermost-to-matrix/venv/lib/python3.10/site-packages/mattermost/__init__.py", line 1315, in create_reaction
Aug 04 19:09:59 uplink python[1887935]:     return self._post("/v4/reactions", data={
Aug 04 19:09:59 uplink python[1887935]:   File "/home/mattermost/mattermost-to-matrix/venv/lib/python3.10/site-packages/mattermost/__init__.py", line 119, in _post
Aug 04 19:09:59 uplink python[1887935]:     raise ApiException(json.loads(res.text))
Aug 04 19:09:59 uplink python[1887935]: mattermost.ApiException: {'id': 'api.reaction.save_reaction.invalid.app_error', 'message': 'Reaction is not valid.', 'detailed_error': '', 'request_id': 'e1df6ouf4fry3cezy98ngseouc', 'status_code>
```

**Comment by gabrc52** [comment]
Can't reproduce normally. The error message is misleading but in this particular case, the error arises when trying to react to a Zephyr message.

When we store which Matrix message corresponds to which Mattermost message, we are not storing messages bridged by the Zephyr bridge.

It's probably tried to react to a mattermost post with ID `None`, which Mattermost refuses to do.
